services:
  - type: web
    name: nestle-artes-ia
    env: static
    buildCommand: "./build.sh"
    staticPublishPath: ./frontend/nestle_application/build/web
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: FLUTTER_WEB
        value: true